cv_list:
    pattern:  /cvs
    defaults: { _controller: MyWebsiteCvBundle:Cv:list}

cv_load:
    pattern:  /cv/{idCv}
    defaults: { _controller: MyWebsiteCvBundle:Cv:load, idCv:0}
    requirements:
        idCv: \d*


cv_profile_list:
    pattern:  /profile/cvs
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileList}

cv_profile_new:
# affiche formCv  #
    pattern:  /profile/cv/new
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileNew}

cv_profile_edit:
# affiche les categories en lecture seule et les contenus en ecriture #
    pattern:  /profile/cv-{idCv}/edit
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileEdit, idCv: 0}
    requirements:
        idCv: \d*

cv_profile_active:
    pattern:  /profile/cv-{idCv}/active-{active}
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileActive, idCv: 0, active: false}
    requirements:
        idCv: \d*
        active: true|false

cv_profile_delete:
    pattern:  /profile/cv-{idCv}/delete
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileDelete, idCv: 0}
    requirements:
        idCv: \d*

cv_profile_category_delete:
    pattern:  /profile/cv/category-{idCategory}/delete
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileCategoryDelete, idCategory: 0}
    requirements:
        idCategory: \d*

cv_profile_category_content_delete:
    pattern:  /profile/cv/category/content-{idContent}/delete
    defaults: { _controller: MyWebsiteCvBundle:Cv:profileContentDelete, idContent: 0}
    requirements:
        idContent: \d*