<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends EntityRepository
{
	public function myFindWithModules($bundleName)
	{
		$qb = $this->createQueryBuilder('bundle')
			->where('bundle.name = :bundle_name')
			->setParameter('bundle_name', $bundleName)
			->leftJoin('bundle.modules', 'module')
			->addSelect('module')
		;
		
		$results = $qb->getQuery()->getResult();
		
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
