<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{	
	public function myFindPictureWithCategoryByProfile($idProfile)
	{
		$qb = $this->createQueryBuilder('document');
		$qb->select('document')
			->leftJoin('document.category', 'category', 'WITH', 'category.tag = :tag')
			->setParameter('tag', 'profile_picture')
			->addSelect('category')
			->leftJoin('category.profile', 'profile', 'WITH', 'profile.id = :id')
			->setParameter('id', $idProfile)
			->addSelect('profile');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
