<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleHandlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleHandlerRepository extends EntityRepository
{
	public function myFindOrdered()
	{
		$qb = $this->createQueryBuilder('moduleHandler')
			->where('moduleHandler.active = :active')
			->setParameter('active', true)
			->addOrderBy('moduleHandler.priority', 'ASC');
	
		return $qb->getQuery()->getResult();
	}
}
