<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleHandlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleHandlerRepository extends EntityRepository
{
	public function myFindOrdered()
	{
		$qb = $this->createQueryBuilder('a');
		$qb->addOrderBy('a.priority', 'DESC');
	
		return $qb->getQuery()->getResult();
	}
}
