<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use MyWebsite\WebBundle\Entity\Menu;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
	public function myFindActivated()
	{
		$qb = $this->createQueryBuilder('module')
			->where('module.active = true')
			->addOrderBy('module.priority', 'ASC')
		;
	
		$results = $qb->getQuery()->getResult();
		
		return $results;
	}
	
	public function myFindActivatedWithMenu()
	{
		$qb = $this->createQueryBuilder('module')
			->where('module.active = :module_active')
			->setParameter('module_active', true)
			->addOrderBy('module.priority', 'ASC')
			->leftJoin('module.menus', 'menu')
			->addSelect('menu')
			->andWhere('menu.isRoot = :isRoot')
			->setParameter('isRoot', true)
			->leftJoin('menu.subMenus', 'subMenu')
			->addSelect('subMenu')
		;
		
		$results = $qb->getQuery()->getResult();
		
		return $results;
	}
	
	public function myFindActivatedWithMenuByDisplay($display)
	{
		$qb = $this->createQueryBuilder('module')
			->where('module.active = :module_active')
			->setParameter('module_active', true)
			->addOrderBy('module.priority', 'ASC')
			->leftJoin('module.menus', 'menu')
			->addSelect('menu')
			->andWhere('menu.display = :menu_display')
			->setParameter('menu_display', $display)
			->andWhere('menu.isRoot = :menu_isRoot')
			->setParameter('menu_isRoot', true)
			->andWhere('menu.active = :menu_active')
			->setParameter('menu_active', true)
		;
		
		$results = $qb->getQuery()->getResult();
		
		return $results;
	}
	
	public function myFindAll()
	{
		$qb = $this->createQueryBuilder('module')
			->addOrderBy('module.priority', 'ASC')
		;
	
		$results = $qb->getQuery()->getResult();
		
		return $results;
	}
}
