<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
	public function myFindActivated()
	{
		$qb = $this->createQueryBuilder('module')
			->where('module.active = :active')
			->setParameter('active', true)
			->addOrderBy('module.priority', 'ASC')
		;
	
		$results = $qb->getQuery()->getResult();
		
		return $results;
	}
}
