<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
	public function myFindWithUser($idProfile)
	{
		$qb = $this->createQueryBuilder('profile');
		$qb->where('profile.id = :id')
			->setParameter('id', $idProfile)
			->leftJoin('profile.user', 'user')
			->addSelect('user');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
	
	public function myFindWithCategories($idProfile)
	{
		$qb = $this->createQueryBuilder('profile');
		$qb->where('profile.id = :id')
			->setParameter('id', $idProfile)
			->leftJoin('profile.categories', 'category')
			->addSelect('category');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
