<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
	public function myFindWithUser($idProfile)
	{
		$qb = $this->createQueryBuilder('profile');
		$qb->where('profile.id = :id')
			->setParameter('id', $idProfile)
			->leftJoin('profile.user', 'user')
			->addSelect('user');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
	
	public function myFindWithCategoriesAndContents($idProfile)
	{
		$qb = $this->createQueryBuilder('profile');
		$qb->where('profile.id = :id')
			->setParameter('id', $idProfile)
			->leftJoin('profile.categories', 'category', 'WITH', 'category.type = :type')
			->setParameter('type', 'content')
			->addSelect('category')
			->leftJoin('category.contents', 'content')
			->addSelect('content');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
	
	public function myFindWithCategoryAndPicture($idProfile)
	{
		$qb = $this->createQueryBuilder('profile');
		$qb->where('profile.id = :id')
			->setParameter('id', $idProfile)
			->leftJoin('profile.categories', 'category', 'WITH', 'category.tag = :tag')
			->setParameter('tag', 'profile_picture')
			->addSelect('category')
			->leftJoin('category.documents', 'document')
			->addSelect('document');
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
