<?php

namespace MyWebsite\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyWebsite\CvBundle\Services\Data;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends EntityRepository
{
	public function myFindWithCategoriesAndContents($idCv)
	{
		$qb = $this->createQueryBuilder('cv')
			->where('cv.id = :id')
			->setParameter('id', $idCv)
			->leftJoin('cv.categories', 'category')
			->addSelect('category')
			->leftJoin('category.contents', 'content')
			->addSelect('content')
		;
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
	
	public function myFindByCategory($idCv, $categoryTitle)
	{
		$qb = $this->createQueryBuilder('cv')
			->where('cv.id = :id')
			->setParameter('id', $idCv)
			->leftJoin('cv.categories', 'category')
			->addSelect('category')
			->andWhere('category.title = :title')
			->setParameter('title', $categoryTitle)
		;
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
