web_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

web_exception_error:
    pattern:  /error
    defaults: { _controller: MyWebsiteWebBundle:Exception:error}
web_exception_error404:
    pattern:  /{errorURL}
    defaults: { _controller: MyWebsiteWebBundle:Exception:error404}
    requirements:
        errorURL: ".*"