cv_list:
    pattern:  /cvs
    defaults: { _controller: MyWebsiteWebBundle:Cv:afficherListCvs}

cv_afficher:
    pattern:  /cv-{idCv}
    defaults: { _controller: MyWebsiteWebBundle:Cv:afficher, idCv:0}
    requirements:
        idCv: \d*

cv_profil_cv_list:
    pattern:  /profil/cvs
    defaults: { _controller: MyWebsiteWebBundle:Profil:listeCv}

cv_profil_cv_afficher:
    pattern:  /profil/cv-{idCv}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionCv, idCv: 0}
    requirements:
        idCv: \d*

cv_profil_cv_nouveau:
    pattern:  /profil/cv/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Cv:nouveau}

cv_profil_cv_modifier:
    pattern:  /profil/cv/modifier-{idCv}-{active}
    defaults: { _controller: MyWebsiteWebBundle:Cv:modifier, idCv: 0, active: false}
    requirements:
        idCv: \d*
        active: true|false

cv_profil_cv_supprimer:
    pattern:  /profil/cv/supprimer-{idCv}
    defaults: { _controller: MyWebsiteWebBundle:Cv:supprimer, idCv: 0}
    requirements:
        idCv: \d*

cv_profil_cv_categorie_afficher:
    pattern:  /profil/cv/categorie-{idCategorie}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionCategorie, idCategorie: 0}
    requirements:
        idCategorie: \d*

cv_profil_cv_categorie_nouveau:
    pattern:  /profil/cv/categorie/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Categorie:nouveau}

cv_profil_cv_categorie_modifier:
    pattern:  /profil/cv/categorie/modifier
    defaults: { _controller: MyWebsiteWebBundle:Categorie:modifier}

cv_profil_cv_categorie_supprimer:
    pattern:  /profil/cv/categorie/supprimer-{idCategorie}
    defaults: { _controller: MyWebsiteWebBundle:Categorie:supprimer, idCategorie: 0}
    requirements:
        idCv: \d*

cv_profil_cv_categorie_contenu_nouveau:
    pattern:  /profil/cv/categorie/contenu/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Contenu:nouveau}

cv_profil_cv_categorie_contenu_modifier:
    pattern:  /profil/cv/categorie/contenu/modifier
    defaults: { _controller: MyWebsiteWebBundle:Contenu:modifier}

cv_profil_cv_categorie_contenu_supprimer:
    pattern:  /profil/cv/categorie/contenu/supprimer-{idContenu}
    defaults: { _controller: MyWebsiteWebBundle:Contenu:supprimer, idContenu: 0}
    requirements:
        idCv: \d*
