cv_home:
    pattern:  /cv
    defaults: { _controller: MyWebsiteCvBundle:Cv:index}

profile_cv:
    pattern:  /profile/cv
    defaults: { _controller: MyWebsiteCvBundle:Cv:load}
profile_cv_list:
    pattern:  /profile/cv/list
    defaults: { _controller: MyWebsiteCvBundle:Cv:list}
profile_cv_new:
    pattern:  /profile/cv/new
    defaults: { _controller: MyWebsiteCvBundle:Cv:new}
profile_cv_edit:
    pattern:  /profile/cv/edit
    defaults: { _controller: MyWebsiteCvBundle:Cv:edit}
profile_cv_model_edit:
    pattern:  /profile/cv/model
    defaults: { _controller: MyWebsiteCvBundle:Cv:editModel}