services:
#    my_website_cv.example:
#        class: MyWebsite\CvBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#   Global services
    cv_router:
        class: MyWebsite\CvBundle\Services\Router
    cv_layouter:
        class: MyWebsite\CvBundle\Services\Layouter
    cv_recorder:
        class: MyWebsite\CvBundle\Services\Recorder
        calls:
            - [setParameters, ["@doctrine.orm.entity_manager", "@service_container"]]
    cv_data:
        class: MyWebsite\CvBundle\Services\Data
    cv_copy:
        class: MyWebsite\CvBundle\Services\Copy
        calls:
            - [setParameters, ["@service_container"]]
#   Form services
    web_form.form.type.cv_cv:
        class: MyWebsite\CvBundle\Form\CvType
        tags:
            - { name: form.type, alias: cv_cv }