<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
	public function myFindAll() 
	{
		$queryb = $this->createQueryBuilder('a');
		$queryb->addOrderBy('a.nom', 'ASC');
	
		return $queryb->getQuery()->getResult();
	}
}
