<?php

namespace MyWebsite\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function myFindAll() 
	{
		$queryb = $this->createQueryBuilder('a');
		$queryb->addOrderBy('a.periode', 'DESC')
				->addOrderBy('a.intitule', 'ASC');
	
		return $queryb->getQuery()->getResult();
	}
}
