mywebsiteweb_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

mywebsiteweb_project_list:
    pattern:  /projects
    defaults: { _controller: MyWebsiteWebBundle:Project:afficherListProjects}

mywebsiteweb_project_afficher:
    pattern:  /project-{idProject}
    defaults: { _controller: MyWebsiteWebBundle:Project:afficher, idProject:0}
    requirements:
        idProject: \d*

mywebsiteweb_cv_list:
    pattern:  /cvs
    defaults: { _controller: MyWebsiteWebBundle:Cv:afficherListCvs}

mywebsiteweb_cv_afficher:
    pattern:  /cv-{idCv}
    defaults: { _controller: MyWebsiteWebBundle:Cv:afficher, idCv:0}
    requirements:
        idProject: \d*

mywebsiteweb_portfolio:
    pattern:  /portfolio
    defaults: { _controller: MyWebsiteWebBundle:Web:portfolio}

mywebsiteweb_contact:
    pattern:  /contact
    defaults: { _controller: MyWebsiteWebBundle:Web:contact}

mywebsiteweb_register:
    pattern:  /register
    defaults: { _controller: MyWebsiteWebBundle:Web:register}

mywebsiteweb_login:
    pattern:  /login
    defaults: { _controller: MyWebsiteWebBundle:Web:login}

mywebsiteweb_logout:
    pattern:  /logout
    defaults: { _controller: MyWebsiteWebBundle:Web:logout}

mywebsiteweb_profil_afficher:
    pattern:  /profil
    defaults: { _controller: MyWebsiteWebBundle:Profil:afficher}

mywebsiteweb_profil_nouveau:
    pattern:  /profil/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Profil:nouveau}

mywebsiteweb_profil_modifier:
    pattern:  /profil/modifier
    defaults: { _controller: MyWebsiteWebBundle:Profil:modifier}

mywebsiteweb_profil_supprimer:
    pattern:  /profil/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Profil:supprimer}

mywebsiteweb_profil_mdp_afficher:
    pattern:  /profil/mdp
    defaults: { _controller: MyWebsiteWebBundle:Profil:afficherMdp}

mywebsiteweb_profil_mdp_modifier:
    pattern:  /profil/mdp/modifier
    defaults: { _controller: MyWebsiteWebBundle:Profil:modifierMdp}

mywebsiteweb_profil_project_list:
    pattern:  /profil/projects
    defaults: { _controller: MyWebsiteWebBundle:Profil:listeProject}

mywebsiteweb_profil_project_nouveau:
    pattern:  /profil/project/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Project:nouveau}

mywebsiteweb_profil_project_afficher:
    pattern:  /profil/project-{idProject}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionProject, idProject: 0}
    requirements:
        idProject: \d*

mywebsiteweb_profil_project_modifier:
    pattern:  /profil/project-{idProject}/modifier
    defaults: { _controller: MyWebsiteWebBundle:Project:modifier, idProject: 0}
    requirements:
        idProject: \d*

mywebsiteweb_profil_project_supprimer:
    pattern:  /profil/project-{idProject}/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Project:supprimer, idProject: 0}
    requirements:
        idProject: \d*

mywebsiteweb_profil_cv_list:
    pattern:  /profil/cvs
    defaults: { _controller: MyWebsiteWebBundle:Profil:listeCv}

mywebsiteweb_profil_cv_nouveau:
    pattern:  /profil/cv/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Cv:nouveau}

mywebsiteweb_profil_cv_afficher:
    pattern:  /profil/cv-{idCv}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionCv, idCv: 0}
    requirements:
        idCv: \d*

mywebsiteweb_profil_cv_modifier:
    pattern:  /profil/cv-{idCv}/modifier-{active}
    defaults: { _controller: MyWebsiteWebBundle:Cv:modifier, idCv: 0, active: false}
    requirements:
        idCv: \d*

mywebsiteweb_profil_cv_supprimer:
    pattern:  /profil/cv-{idCv}/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Cv:supprimer, idCv: 0}
    requirements:
        idCv: \d*

mywebsiteweb_profil_cv_categorie_nouveau:
    pattern:  /profil/cv-{idCv}/categorie/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Categorie:nouveau, idCv: 0}
    requirements:
        idCv: \d*

mywebsiteweb_profil_cv_categorie_afficher:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionCategorie, idCv: 0, idCategorie: 0}
    requirements:
        idCv: \d*
        idCategorie: \d*

mywebsiteweb_profil_cv_categorie_modifier:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}/modifier
    defaults: { _controller: MyWebsiteWebBundle:Categorie:modifier, idCv:0, idCategorie: 0}
    requirements:
        idCv: \d*
        idCategorie: \d*

mywebsiteweb_profil_cv_categorie_supprimer:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Categorie:supprimer, idCv:0, idCategorie: 0}
    requirements:
        idCv: \d*
        idCategorie: \d*

mywebsiteweb_profil_cv_categorie_contenu_nouveau:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}/contenu/nouveau
    defaults: { _controller: MyWebsiteWebBundle:Contenu:nouveau, idCv:0, idCategorie:0}
    requirements:
        idCv: \d*
        idCategorie: \d*

mywebsiteweb_profil_cv_categorie_contenu_modifier:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}/contenu-{idContenu}/modifier
    defaults: { _controller: MyWebsiteWebBundle:Contenu:modifier, idContenu: 0}
    requirements:
        idCv: \d*
        idCategorie: \d*
        idContenu: \d*

mywebsiteweb_profil_cv_categorie_contenu_supprimer:
    pattern:  /profil/cv-{idCv}/categorie-{idCategorie}/contenu-{idContenu}/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Contenu:supprimer, idContenu: 0}
    requirements:
        idCv: \d*
        idCategorie: \d*
        idContenu: \d*

mywebsiteweb_profil_portfolio_list:
    pattern:  /profil/portfolios
    defaults: { _controller: MyWebsiteWebBundle:Profil:listePortfolio}

mywebsiteweb_profil_portfolio_afficher:
    pattern:  /profil/portfolio-{idPortfolio}
    defaults: { _controller: MyWebsiteWebBundle:Profil:gestionPortfolio, idPortfolio: 0}