profile_user:
    pattern:  /user
    defaults: { _controller: MyWebsiteProfileBundle:User:load}
profile_user_signup:
    pattern:  /signup
    defaults: { _controller: MyWebsiteProfileBundle:User:signup}
profile_user_logout:
    pattern:  /logout
    defaults: { _controller: MyWebsiteProfileBundle:User:logout}
profile_user_upgrade:
    pattern:  /user/upgrade
    defaults: { _controller: MyWebsiteProfileBundle:User:upgrade}
profile_user_downgrade:
    pattern:  /user/downgrade
    defaults: { _controller: MyWebsiteProfileBundle:User:downgrade}

profile_admin:
    pattern:  /admin
    defaults: { _controller: MyWebsiteProfileBundle:Admin:load}
profile_admin_info:
    pattern:  /admin/info
    defaults: { _controller: MyWebsiteProfileBundle:Admin:edit}

profile_client:
    pattern:  /profile
    defaults: { _controller: MyWebsiteProfileBundle:Client:load}
profile_client_info:
    pattern:  /profile/info
    defaults: { _controller: MyWebsiteProfileBundle:Client:edit}
profile_client_picture:
    pattern:  /profile/picture
    defaults: { _controller: MyWebsiteProfileBundle:Client:editPicture}
profile_client_picture_delete:
    pattern:  /profile/picture/delete
    defaults: { _controller: MyWebsiteProfileBundle:Client:deletePicture}
profile_client_delete:
    pattern:  /profile/delete
    defaults: { _controller: MyWebsiteProfileBundle:Client:delete}