services:
#    my_website_profile.example:
#        class: MyWebsite\ProfileBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#   Global services
    profile_router:
        class: MyWebsite\ProfileBundle\Services\Router
    profile_layouter:
        class: MyWebsite\ProfileBundle\Services\Layouter
    profile_recorder:
        class: MyWebsite\ProfileBundle\Services\Recorder
        calls:
            - [setParameters, ["@doctrine.orm.entity_manager", "@service_container"]]
    profile_data:
        class: MyWebsite\ProfileBundle\Services\Data

#   Form services
    web_form.form.type.profile_user:
        class: MyWebsite\ProfileBundle\Form\UserType
        tags:
            - { name: form.type, alias: profile_user }
    web_form.form.type.profile_admin:
        class: MyWebsite\ProfileBundle\Form\AdminType
        tags:
            - { name: form.type, alias: profile_admin }
    web_form.form.type.profile_client:
        class: MyWebsite\ProfileBundle\Form\ClientType
        tags:
            - { name: form.type, alias: profile_client }

