<?php

namespace MyWebsite\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyWebsite\WebBundle\Entity\Category;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
	public function myFindWithCategoriesAndContents($idAdmin)
	{
		$qb = $this->createQueryBuilder('client')
			->where('client.id = :id')
			->setParameter('id', $idAdmin)
			->leftJoin('client.categories', 'category', 'WITH', 'category.type = :type')
			->setParameter('type', 'content')
			->addSelect('category')
			->leftJoin('category.contents', 'content')
			->addSelect('content')
		;
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
	
	public function myFindWithCategoryAndPicture($idAdmin)
	{
		$qb = $this->createQueryBuilder('client')
			->where('client.id = :id')
			->setParameter('id', $idAdmin)
			->leftJoin('client.categories', 'category', 'WITH', 'category.tag = :tag')
			->setParameter('tag', Category::TAG_PROFILE_PICTURE)
			->addSelect('category')
			->leftJoin('category.documents', 'document')
			->addSelect('document')
		;
		
		$results = $qb->getQuery()->getResult();
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
