<?php

namespace MyWebsite\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyWebsite\ProfileBundle\Services\ProfileData;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
	public function myFindWithCategoriesAndContents($idAdmin)
	{
		$qb = $this->createQueryBuilder('client')
			->where('client.id = :id')
			->setParameter('id', $idAdmin)
			->leftJoin('client.categories', 'category')
			->addSelect('category')
			->leftJoin('category.contents', 'content')
			->addSelect('content')
		;
		
		$results = $qb->getQuery()->getResult();
		die(var_dump($results));
		if($results == null)
		{
			return null;
		}
		
		return $results[0];
	}
}
