web_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

web_login:
    pattern:  /login
    defaults: { _controller: MyWebsiteWebBundle:Web:login}

web_logout:
    pattern:  /logout
    defaults: { _controller: MyWebsiteWebBundle:Web:logout}

web_profil_afficher:
    pattern:  /profil
    defaults: { _controller: MyWebsiteWebBundle:Profil:afficher}

web_profil_modifier:
    pattern:  /profil/picture/modifier
    defaults: { _controller: MyWebsiteWebBundle:Profil:modifierPicture, displayPicture: true}
    requirements:
        displayPicture: true|false

web_profil_picture_supprimer:
    pattern:  /profil/picture/supprimer
    defaults: { _controller: MyWebsiteWebBundle:Profil:supprimerPicture}

web_profil_admin_afficher:
    pattern:  /profil/admin
    defaults: { _controller: MyWebsiteWebBundle:Profil:afficherMdp}

web_profil_admin_modifier:
    pattern:  /profil/admin/modifier
    defaults: { _controller: MyWebsiteWebBundle:Profil:modifierMdp}