web_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

web_profile_signup:
    pattern:  /signup
    defaults: { _controller: MyWebsiteWebBundle:User:signup}

web_profile_user:
    pattern:  /user
    defaults: { _controller: MyWebsiteWebBundle:User:edit}

web_profile_logout:
    pattern:  /logout
    defaults: { _controller: MyWebsiteWebBundle:User:logout}

web_client:
    pattern:  /client
    defaults: { _controller: MyWebsiteWebBundle:Client:load}

web_client_info:
    pattern:  /client/info
    defaults: { _controller: MyWebsiteWebBundle:Client:edit}

web_client_picture:
    pattern:  /client/picture
    defaults: { _controller: MyWebsiteWebBundle:Client:editPicture}

web_client_picture_delete:
    pattern:  /client/picture/delete
    defaults: { _controller: MyWebsiteWebBundle:Client:deletePicture}

web_client_delete:
    pattern:  /client/delete
    defaults: { _controller: MyWebsiteWebBundle:Client:delete}

web_admin:
    pattern:  /admin
    defaults: { _controller: MyWebsiteWebBundle:Admin:load}

web_admin_info:
    pattern:  /client/info
    defaults: { _controller: MyWebsiteWebBundle:Admin:edit}

web_admin_delete:
    pattern:  /client/delete
    defaults: { _controller: MyWebsiteWebBundle:Admin:delete}

web_error:
    pattern:  /error
    defaults: { _controller: MyWebsiteWebBundle:Exception:error}

web_error404:
    pattern:  /{errorURL}
    defaults: { _controller: MyWebsiteWebBundle:Exception:error404}
    requirements:
        errorURL: ".*"