web_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

web_signup:
    pattern:  /signup
    defaults: { _controller: MyWebsiteWebBundle:Profile:newProfile}

web_profile:
    pattern:  /profile
    defaults: { _controller: MyWebsiteWebBundle:Profile:loadProfile}

web_profile_info:
    pattern:  /profile/info
    defaults: { _controller: MyWebsiteWebBundle:Profile:editProfile}

web_profile_picture:
    pattern:  /profile/picture
    defaults: { _controller: MyWebsiteWebBundle:Profile:editPicture}

web_profile_picture_delete:
    pattern:  /profile/picture/delete
    defaults: { _controller: MyWebsiteWebBundle:Profile:deletePicture}

web_profile_user:
    pattern:  /profile/user
    defaults: { _controller: MyWebsiteWebBundle:Profile:editUser}

web_profile_logout:
    pattern:  /profile/logout
    defaults: { _controller: MyWebsiteWebBundle:Profile:logout}

web_admin:
    pattern:  /admin
    defaults: { _controller: MyWebsiteWebBundle:Admin:loadAdmin}

web_error:
    pattern:  /error
    defaults: { _controller: MyWebsiteWebBundle:Exception:error}

web_error404:
    pattern:  /{errorURL}
    defaults: { _controller: MyWebsiteWebBundle:Exception:error404}
    requirements:
        errorURL: ".*"