web_home:
    pattern:  /
    defaults: { _controller: MyWebsiteWebBundle:Web:index}

web_profile:
    pattern:  /profile
    defaults: { _controller: MyWebsiteWebBundle:Profile:load}

web_profile_edit:
    pattern:  /profile/edit
    defaults: { _controller: MyWebsiteWebBundle:Profile:edit}

web_profile_logout:
    pattern:  /profile/logout
    defaults: { _controller: MyWebsiteWebBundle:Profile:logout}

web_profile_picture_load:
    pattern:  /profile/picture
    defaults: { _controller: MyWebsiteWebBundle:Profile:loadPicture}

web_profile_picture_edit:
    pattern:  /profile/picture/edit
    defaults: { _controller: MyWebsiteWebBundle:Profile:editPicture, displayPicture: true}
    requirements:
        displayPicture: true|false

web_profile_picture_delete:
    pattern:  /profile/picture/delete
    defaults: { _controller: MyWebsiteWebBundle:Profile:deletePicture}

web_profile_user_load:
    pattern:  /profile/user
    defaults: { _controller: MyWebsiteWebBundle:User:loadUser}

web_profile_user_edit:
    pattern:  /profile/user/edit
    defaults: { _controller: MyWebsiteWebBundle:User:editUser}

web_profile_error:
    pattern:  /profile/error
    defaults: { _controller: MyWebsiteWebBundle:Exception:error}

web_error404:
    pattern:  /{errorURL}
    defaults: { _controller: MyWebsiteWebBundle:Exception:error404}
    requirements:
        errorURL: ".*"