parameters:
#    mywebsiteweb.example.class: MyWebsite\WebBundle\Example

services:
#    mywebsiteweb.example:
#        class: %mywebsiteweb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    kernel.listener.web_cache_listener:
        class: MyWebsite\WebBundle\Listener\WebCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    web_router:
        class: MyWebsite\WebBundle\Services\Router
    web_layouter:
        class: MyWebsite\WebBundle\Services\Layouter
    web_moduleHandler:
        class: MyWebsite\WebBundle\Services\ModuleHandler
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
    web_generator:
        class: MyWebsite\WebBundle\Services\Generator
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
